SELECT --[SalesQuotaKey] 
     -- ,[EmployeeKey]
   --   [DateKey] 
 --     ,[CalendarYear]
 --     ,[CalendarQuarter]
      [SalesAmountQuota] AS [Budget]
      ,[Date]
  FROM [AdventureWorksDW2022].[dbo].[FactSalesQuota]
